services:
  - type: web
    name: hrms-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m flask db upgrade && python3 -m flask seed-core && python3 -m flask seed-rbac && gunicorn "hrms_api.wsgi:app" --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    autoDeploy: true
    envVars:
      - key: FLASK_APP
        value: hrms_api.wsgi:app
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: hrms-pg
          property: connectionString

databases:
  - name: hrms-pg
    plan: free
