"""leave overlay indexes

Revision ID: 0dc9c66eeefc
Revises: 9a7e69fd3985
Create Date: 2025-09-16 09:23:55.519997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dc9c66eeefc'
down_revision: Union[str, Sequence[str], None] = '9a7e69fd3985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
