"""attendance v2: punches + shifts + missed + rollup

Revision ID: 107a380f5668
Revises: 81cd6ca192cd
Create Date: 2025-11-13 18:52:03.242707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "107a380f5668"
down_revision: Union[str, Sequence[str], None] = "81cd6ca192cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "attendance_punches",
        sa.Column("company_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "attendance_punches",
        sa.Column("direction", sa.String(length=8), nullable=True),
    )
    op.add_column(
        "attendance_punches",
        sa.Column("method", sa.String(length=16), nullable=True),
    )
    op.add_column(
        "attendance_punches",
        sa.Column("device_id", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "attendance_punches",
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=True),
    )
    op.add_column(
        "attendance_punches",
        sa.Column("lon", sa.Numeric(precision=9, scale=6), nullable=True),
    )
    op.add_column(
        "attendance_punches",
        sa.Column("accuracy_m", sa.Numeric(precision=6, scale=2), nullable=True),
    )
    op.add_column(
        "attendance_punches",
        sa.Column("photo_url", sa.Text(), nullable=True),
    )
    op.add_column(
        "attendance_punches",
        sa.Column("face_score", sa.Numeric(precision=4, scale=3), nullable=True),
    )
    op.add_column(
        "attendance_punches",
        sa.Column(
            "source_meta",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "attendance_punches",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "attendance_punches",
        "note",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_punch_emp_ts"), table_name="attendance_punches")
    op.create_index(
        op.f("ix_attendance_punches_company_id"),
        "attendance_punches",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_punches_device_id"),
        "attendance_punches",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_punches_method"),
        "attendance_punches",
        ["method"],
        unique=False,
    )
    op.create_index(
        "ix_punch_company_ts",
        "attendance_punches",
        ["company_id", "ts"],
        unique=False,
    )
    op.create_index(
        "ix_punch_employee_ts",
        "attendance_punches",
        ["employee_id", "ts"],
        unique=False,
    )
    op.create_index(
        "ix_punch_method_ts",
        "attendance_punches",
        ["method", "ts"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_punch_employee_ts_dir",
        "attendance_punches",
        ["employee_id", "ts", "direction"],
    )
    op.drop_column("attendance_punches", "kind")
    op.drop_column("attendance_punches", "source")

    # --- Locations geo fencing fields ---
    op.add_column(
        "locations",
        sa.Column("geo_lat", sa.Numeric(precision=9, scale=6), nullable=True),
    )
    op.add_column(
        "locations",
        sa.Column("geo_lon", sa.Numeric(precision=9, scale=6), nullable=True),
    )
    # Make this nullable so existing rows don’t violate NOT NULL
    op.add_column(
        "locations",
        sa.Column("geo_radius_m", sa.Integer(), nullable=True),
    )

    op.create_index(
        "ix_statcfg_active_window",
        "stat_configs",
        ["type", "scope", "company_id", "state", "key", "effective_from", "effective_to"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_statcfg_active_window", table_name="stat_configs")
    op.drop_column("locations", "geo_radius_m")
    op.drop_column("locations", "geo_lon")
    op.drop_column("locations", "geo_lat")

    op.add_column(
        "attendance_punches",
        sa.Column("source", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    )
    op.add_column(
        "attendance_punches",
        sa.Column("kind", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        "uq_punch_employee_ts_dir",
        "attendance_punches",
        type_="unique",
    )
    op.drop_index("ix_punch_method_ts", table_name="attendance_punches")
    op.drop_index("ix_punch_employee_ts", table_name="attendance_punches")
    op.drop_index("ix_punch_company_ts", table_name="attendance_punches")
    op.drop_index(op.f("ix_attendance_punches_method"), table_name="attendance_punches")
    op.drop_index(
        op.f("ix_attendance_punches_device_id"),
        table_name="attendance_punches",
    )
    op.drop_index(
        op.f("ix_attendance_punches_company_id"),
        table_name="attendance_punches",
    )
    op.create_index(
        op.f("ix_punch_emp_ts"),
        "attendance_punches",
        ["employee_id", "ts"],
        unique=False,
    )
    op.alter_column(
        "attendance_punches",
        "note",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
    op.drop_column("attendance_punches", "updated_at")
    op.drop_column("attendance_punches", "source_meta")
    op.drop_column("attendance_punches", "face_score")
    op.drop_column("attendance_punches", "photo_url")
    op.drop_column("attendance_punches", "accuracy_m")
    op.drop_column("attendance_punches", "lon")
    op.drop_column("attendance_punches", "lat")
    op.drop_column("attendance_punches", "device_id")
    op.drop_column("attendance_punches", "method")
    op.drop_column("attendance_punches", "direction")
    op.drop_column("attendance_punches", "company_id")
    # ### end Alembic commands ###
