"""Add RGS tables

Revision ID: 1f6c93b52daf
Revises: d48c8c6d33c0
Create Date: 2025-11-26 08:25:46.168475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f6c93b52daf'
down_revision: Union[str, Sequence[str], None] = 'd48c8c6d33c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rgs_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('query_template', sa.Text(), nullable=False),
    sa.Column('output_format', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_rgs_reports_category', 'rgs_reports', ['category'], unique=False)
    op.create_table('rgs_report_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.String(length=255), nullable=True),
    sa.Column('enum_values', sa.JSON(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['rgs_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rgs_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['rgs_reports.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rgs_runs_report_status', 'rgs_runs', ['report_id', 'status'], unique=False)
    op.create_index('ix_rgs_runs_user', 'rgs_runs', ['requested_by_user_id'], unique=False)
    op.create_table('rgs_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['rgs_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'geo_radius_m',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('attendance_punches', 'direction',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('attendance_punches', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('rgs_outputs')
    op.drop_index('ix_rgs_runs_user', table_name='rgs_runs')
    op.drop_index('ix_rgs_runs_report_status', table_name='rgs_runs')
    op.drop_table('rgs_runs')
    op.drop_table('rgs_report_parameters')
    op.drop_index('ix_rgs_reports_category', table_name='rgs_reports')
    op.drop_table('rgs_reports')
    # ### end Alembic commands ###
