"""Update leave models

Revision ID: 25c62b394c7d
Revises: 3827dd61c665
Create Date: 2025-11-29 12:22:47.261872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25c62b394c7d'
down_revision: Union[str, Sequence[str], None] = '3827dd61c665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_leave_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('accrued', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('used', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('adjusted', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'leave_type_id', 'year', name='uq_emp_leave_bal_year')
    )
    op.create_index(op.f('ix_employee_leave_balances_employee_id'), 'employee_leave_balances', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_leave_balances_leave_type_id'), 'employee_leave_balances', ['leave_type_id'], unique=False)
    op.create_table('comp_off_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('date_earned', sa.Date(), nullable=False),
    sa.Column('hours_or_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('linked_leave_request_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_leave_request_id'], ['leave_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comp_off_credits_employee_id'), 'comp_off_credits', ['employee_id'], unique=False)
    op.create_table('leave_approval_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leave_request_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('acted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('acted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['leave_request_id'], ['leave_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_approval_actions_leave_request_id'), 'leave_approval_actions', ['leave_request_id'], unique=False)
    op.drop_index(op.f('ix_leave_balances_employee_id'), table_name='leave_balances')
    op.drop_index(op.f('ix_leave_balances_leave_type_id'), table_name='leave_balances')
    op.drop_table('leave_balances')
    # op.alter_column('attendance_punches', 'company_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # op.alter_column('attendance_punches', 'direction',
    #            existing_type=sa.VARCHAR(length=8),
    #            nullable=False)
    op.add_column('leave_requests', sa.Column('company_id', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('leave_requests', sa.Column('is_half_day', sa.Boolean(), nullable=True))
    op.add_column('leave_requests', sa.Column('total_days', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0'))
    op.add_column('leave_requests', sa.Column('applied_by_user_id', sa.Integer(), nullable=True))
    op.add_column('leave_requests', sa.Column('approved_by_user_id', sa.Integer(), nullable=True))
    op.add_column('leave_requests', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('leave_requests', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('leave_requests', 'reason',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_leave_requests_company_id'), 'leave_requests', ['company_id'], unique=False)
    op.drop_constraint(op.f('leave_requests_approver_id_fkey'), 'leave_requests', type_='foreignkey')
    op.create_foreign_key(None, 'leave_requests', 'users', ['approved_by_user_id'], ['id'])
    op.create_foreign_key(None, 'leave_requests', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'leave_requests', 'users', ['applied_by_user_id'], ['id'])
    op.drop_column('leave_requests', 'days')
    op.drop_column('leave_requests', 'approver_id')
    op.drop_column('leave_requests', 'part_day')
    op.add_column('leave_types', sa.Column('is_paid', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('leave_types', sa.Column('is_comp_off', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('leave_types', sa.Column('allow_half_day', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('leave_types', sa.Column('requires_document', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('leave_types', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('leave_types', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('leave_types', 'active')
    op.drop_column('leave_types', 'accrual_per_month')
    op.drop_column('leave_types', 'paid')
    op.drop_column('leave_types', 'negative_balance_allowed')
    op.drop_column('leave_types', 'unit')
    op.drop_column('leave_types', 'carry_forward_limit')
    op.drop_column('leave_types', 'requires_approval')
    # op.alter_column('locations', 'geo_radius_m',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'geo_radius_m',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('leave_types', sa.Column('requires_approval', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('leave_types', sa.Column('carry_forward_limit', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True))
    op.add_column('leave_types', sa.Column('unit', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('leave_types', sa.Column('negative_balance_allowed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('leave_types', sa.Column('paid', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('leave_types', sa.Column('accrual_per_month', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.add_column('leave_types', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('leave_types', 'updated_at')
    op.drop_column('leave_types', 'is_active')
    op.drop_column('leave_types', 'requires_document')
    op.drop_column('leave_types', 'allow_half_day')
    op.drop_column('leave_types', 'is_comp_off')
    op.drop_column('leave_types', 'is_paid')
    op.add_column('leave_requests', sa.Column('part_day', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('leave_requests', sa.Column('approver_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('leave_requests', sa.Column('days', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.drop_constraint(None, 'leave_requests', type_='foreignkey')
    op.create_foreign_key(op.f('leave_requests_approver_id_fkey'), 'leave_requests', 'users', ['approver_id'], ['id'])
    op.drop_index(op.f('ix_leave_requests_company_id'), table_name='leave_requests')
    op.alter_column('leave_requests', 'reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('leave_requests', 'updated_at')
    op.drop_column('leave_requests', 'rejection_reason')
    op.drop_column('leave_requests', 'approved_by_user_id')
    op.drop_column('leave_requests', 'applied_by_user_id')
    op.drop_column('leave_requests', 'total_days')
    op.drop_column('leave_requests', 'is_half_day')
    op.drop_column('leave_requests', 'company_id')
    op.alter_column('attendance_punches', 'direction',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('attendance_punches', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('leave_balances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('leave_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('ytd_accrued', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('ytd_taken', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('leave_balances_employee_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], name=op.f('leave_balances_leave_type_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('leave_balances_pkey')),
    sa.UniqueConstraint('employee_id', 'leave_type_id', name=op.f('uq_leave_balance_emp_type'))
    )
    op.create_index(op.f('ix_leave_balances_leave_type_id'), 'leave_balances', ['leave_type_id'], unique=False)
    op.create_index(op.f('ix_leave_balances_employee_id'), 'leave_balances', ['employee_id'], unique=False)
    op.drop_index(op.f('ix_leave_approval_actions_leave_request_id'), table_name='leave_approval_actions')
    op.drop_table('leave_approval_actions')
    op.drop_index(op.f('ix_comp_off_credits_employee_id'), table_name='comp_off_credits')
    op.drop_table('comp_off_credits')
    op.drop_index(op.f('ix_employee_leave_balances_leave_type_id'), table_name='employee_leave_balances')
    op.drop_index(op.f('ix_employee_leave_balances_employee_id'), table_name='employee_leave_balances')
    op.drop_table('employee_leave_balances')
    # ### end Alembic commands ###
