"""Add attendance_rollups table

Revision ID: 3827dd61c665
Revises: 1f6c93b52daf
Create Date: 2025-11-26 15:52:20.524886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3827dd61c665'
down_revision: Union[str, Sequence[str], None] = '1f6c93b52daf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_rollups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('present_days', sa.Float(), nullable=True),
    sa.Column('absent_days', sa.Float(), nullable=True),
    sa.Column('leave_days', sa.Float(), nullable=True),
    sa.Column('weekly_off_days', sa.Float(), nullable=True),
    sa.Column('holiday_days', sa.Float(), nullable=True),
    sa.Column('lop_days', sa.Float(), nullable=True),
    sa.Column('ot_hours', sa.Float(), nullable=True),
    sa.Column('total_working_days', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'year', 'month', name='uq_attendance_rollup_emp_month')
    )
    op.create_index('ix_attendance_rollup_period', 'attendance_rollups', ['company_id', 'year', 'month'], unique=False)
    op.create_index(op.f('ix_attendance_rollups_company_id'), 'attendance_rollups', ['company_id'], unique=False)
    op.create_index(op.f('ix_attendance_rollups_employee_id'), 'attendance_rollups', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'geo_radius_m',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('attendance_punches', 'direction',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('attendance_punches', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_attendance_rollups_employee_id'), table_name='attendance_rollups')
    op.drop_index(op.f('ix_attendance_rollups_company_id'), table_name='attendance_rollups')
    op.drop_index('ix_attendance_rollup_period', table_name='attendance_rollups')
    op.drop_table('attendance_rollups')
    # ### end Alembic commands ###
