"""delete function update- company-masters

Revision ID: 42e60fe473cd
Revises: b7ff0da2b361
Create Date: 2025-09-18 17:02:12.312423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e60fe473cd'
down_revision: Union[str, Sequence[str], None] = 'b7ff0da2b361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'deleted_at')
    # ### end Alembic commands ###
