"""Add leave_policies table

Revision ID: 436d71d8e38b
Revises: 25c62b394c7d
Create Date: 2025-11-29 13:13:38.027294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '436d71d8e38b'
down_revision: Union[str, Sequence[str], None] = '25c62b394c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('entitlement_per_year', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('carry_forward_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('allow_negative', sa.Boolean(), nullable=True),
    sa.Column('max_negative_balance', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('accrual_pattern', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'leave_type_id', 'grade_id', 'year', name='uq_leave_policy_company_type_grade_year')
    )
    # op.alter_column('attendance_punches', 'company_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # op.alter_column('attendance_punches', 'direction',
    #            existing_type=sa.VARCHAR(length=8),
    #            nullable=False)
    # op.alter_column('locations', 'geo_radius_m',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('locations', 'geo_radius_m',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.alter_column('attendance_punches', 'direction',
    #            existing_type=sa.VARCHAR(length=8),
    #            nullable=True)
    # op.alter_column('attendance_punches', 'company_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    op.drop_table('leave_policies')
    # ### end Alembic commands ###
