"""create trade_categories

Revision ID: 4561e498a7fd
Revises: 97f50f61a0d8
Create Date: 2025-10-24 11:43:26.685764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4561e498a7fd'
down_revision: Union[str, Sequence[str], None] = '97f50f61a0d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('per_day_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ot_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_wage_zone', sa.String(length=32), nullable=True),
    sa.Column('min_wage_skill', sa.String(length=32), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_categories_code'), 'trade_categories', ['code'], unique=False)
    op.create_index(op.f('ix_trade_categories_effective_from'), 'trade_categories', ['effective_from'], unique=False)
    op.create_index(op.f('ix_trade_categories_effective_to'), 'trade_categories', ['effective_to'], unique=False)
    op.create_index(op.f('ix_trade_categories_is_active'), 'trade_categories', ['is_active'], unique=False)
    op.create_index('ix_trade_code_effective', 'trade_categories', ['code', 'effective_from', 'effective_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trade_code_effective', table_name='trade_categories')
    op.drop_index(op.f('ix_trade_categories_is_active'), table_name='trade_categories')
    op.drop_index(op.f('ix_trade_categories_effective_to'), table_name='trade_categories')
    op.drop_index(op.f('ix_trade_categories_effective_from'), table_name='trade_categories')
    op.drop_index(op.f('ix_trade_categories_code'), table_name='trade_categories')
    op.drop_table('trade_categories')
    # ### end Alembic commands ###
