"""employees core

Revision ID: 6b147c7f7ea6
Revises: f4da4b43594e
Create Date: 2025-09-14 17:35:22.504704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b147c7f7ea6'
down_revision: Union[str, Sequence[str], None] = 'f4da4b43594e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('designation_id', sa.Integer(), nullable=True),
    sa.Column('grade_id', sa.Integer(), nullable=True),
    sa.Column('cost_center_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('doj', sa.Date(), nullable=True),
    sa.Column('dol', sa.Date(), nullable=True),
    sa.Column('employment_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_employee_company_code'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_emp_company_id', 'employees', ['company_id'], unique=False)
    op.create_index('ix_emp_dept_id', 'employees', ['department_id'], unique=False)
    op.create_index('ix_emp_location_id', 'employees', ['location_id'], unique=False)
    op.create_index('ix_emp_manager_id', 'employees', ['manager_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emp_manager_id', table_name='employees')
    op.drop_index('ix_emp_location_id', table_name='employees')
    op.drop_index('ix_emp_dept_id', table_name='employees')
    op.drop_index('ix_emp_company_id', table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
