"""add user_id to employees

Revision ID: 9310bfe71a8b
Revises: 436d71d8e38b
Create Date: 2025-11-29 13:55:30.161767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9310bfe71a8b'
down_revision: Union[str, Sequence[str], None] = '436d71d8e38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('attendance_punches', 'company_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # op.alter_column('attendance_punches', 'direction',
    #            existing_type=sa.VARCHAR(length=8),
    #            nullable=False)
    op.add_column('employees', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'employees', ['user_id'])
    op.create_foreign_key(None, 'employees', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # op.alter_column('locations', 'geo_radius_m',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'geo_radius_m',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'user_id')
    op.alter_column('attendance_punches', 'direction',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('attendance_punches', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
