"""attendance punches + daily status

Revision ID: 9481fdaad6fc
Revises: dc7061332734
Create Date: 2025-09-14 21:54:09.068869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9481fdaad6fc'
down_revision: Union[str, Sequence[str], None] = 'dc7061332734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_punches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("kind in ('in','out')", name='ck_punch_kind'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_punches_employee_id'), 'attendance_punches', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_punches_ts'), 'attendance_punches', ['ts'], unique=False)
    op.create_index('ix_punch_emp_ts', 'attendance_punches', ['employee_id', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_punch_emp_ts', table_name='attendance_punches')
    op.drop_index(op.f('ix_attendance_punches_ts'), table_name='attendance_punches')
    op.drop_index(op.f('ix_attendance_punches_employee_id'), table_name='attendance_punches')
    op.drop_table('attendance_punches')
    # ### end Alembic commands ###
