"""attendance masters: holidays, weekly off rules, shifts

Revision ID: a533891375cd
Revises: a7dfc8a61b41
Create Date: 2025-09-14 18:14:54.558529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a533891375cd'
down_revision: Union[str, Sequence[str], None] = 'a7dfc8a61b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.Column('grace_minutes', sa.Integer(), nullable=False),
    sa.Column('is_night', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_shift_company_code')
    )
    op.create_index(op.f('ix_shifts_company_id'), 'shifts', ['company_id'], unique=False)
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'location_id', 'date', name='uq_holiday_company_location_date')
    )
    op.create_index(op.f('ix_holidays_company_id'), 'holidays', ['company_id'], unique=False)
    op.create_index(op.f('ix_holidays_location_id'), 'holidays', ['location_id'], unique=False)
    op.create_table('weekly_off_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('is_alternate', sa.Boolean(), nullable=False),
    sa.Column('week_numbers', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'location_id', 'weekday', 'is_alternate', 'week_numbers', name='uq_weekoff_rule')
    )
    op.create_index(op.f('ix_weekly_off_rules_company_id'), 'weekly_off_rules', ['company_id'], unique=False)
    op.create_index(op.f('ix_weekly_off_rules_location_id'), 'weekly_off_rules', ['location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_off_rules_location_id'), table_name='weekly_off_rules')
    op.drop_index(op.f('ix_weekly_off_rules_company_id'), table_name='weekly_off_rules')
    op.drop_table('weekly_off_rules')
    op.drop_index(op.f('ix_holidays_location_id'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_company_id'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_shifts_company_id'), table_name='shifts')
    op.drop_table('shifts')
    # ### end Alembic commands ###
