"""employee addresses + bank accounts

Revision ID: a7dfc8a61b41
Revises: 6b147c7f7ea6
Create Date: 2025-09-14 17:59:00.422346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7dfc8a61b41'
down_revision: Union[str, Sequence[str], None] = '6b147c7f7ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('line1', sa.String(length=120), nullable=False),
    sa.Column('line2', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('state', sa.String(length=60), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'type', name='uq_empaddr_emp_type')
    )
    op.create_index('ix_empaddr_primary', 'employee_addresses', ['employee_id', 'is_primary'], unique=False)
    op.create_index(op.f('ix_employee_addresses_employee_id'), 'employee_addresses', ['employee_id'], unique=False)
    op.create_table('employee_bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=80), nullable=False),
    sa.Column('ifsc', sa.String(length=20), nullable=False),
    sa.Column('account_number', sa.String(length=40), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_empbank_primary', 'employee_bank_accounts', ['employee_id', 'is_primary'], unique=False)
    op.create_index(op.f('ix_employee_bank_accounts_employee_id'), 'employee_bank_accounts', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_bank_accounts_employee_id'), table_name='employee_bank_accounts')
    op.drop_index('ix_empbank_primary', table_name='employee_bank_accounts')
    op.drop_table('employee_bank_accounts')
    op.drop_index(op.f('ix_employee_addresses_employee_id'), table_name='employee_addresses')
    op.drop_index('ix_empaddr_primary', table_name='employee_addresses')
    op.drop_table('employee_addresses')
    # ### end Alembic commands ###
