"""add_face_attendance_models

Revision ID: d48c8c6d33c0
Revises: 107a380f5668
Create Date: 2025-11-25 17:14:31.808868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd48c8c6d33c0'
down_revision: Union[str, Sequence[str], None] = '107a380f5668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_face_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding_version', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_face_profiles_employee_id'), 'employee_face_profiles', ['employee_id'], unique=False)
    op.create_table('face_attendance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('punch_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('req_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('req_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('location_status', sa.String(length=50), nullable=False),
    sa.Column('face_status', sa.String(length=50), nullable=False),
    sa.Column('face_similarity', sa.Float(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('punch_type', sa.String(length=10), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['punch_id'], ['attendance_punches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_attendance_logs_employee_id'), 'face_attendance_logs', ['employee_id'], unique=False)
    op.add_column('attendance_punches', sa.Column('location_id', sa.Integer(), nullable=True))
    # op.alter_column('attendance_punches', 'company_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # op.alter_column('attendance_punches', 'direction',
    #            existing_type=sa.VARCHAR(length=8),
    #            nullable=False)
    op.create_index(op.f('ix_attendance_punches_location_id'), 'attendance_punches', ['location_id'], unique=False)
    op.create_foreign_key(None, 'attendance_punches', 'locations', ['location_id'], ['id'], ondelete='SET NULL')
    # op.alter_column('locations', 'geo_radius_m',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'geo_radius_m',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'attendance_punches', type_='foreignkey')
    op.drop_index(op.f('ix_attendance_punches_location_id'), table_name='attendance_punches')
    op.alter_column('attendance_punches', 'direction',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
    op.alter_column('attendance_punches', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('attendance_punches', 'location_id')
    op.drop_index(op.f('ix_face_attendance_logs_employee_id'), table_name='face_attendance_logs')
    op.drop_table('face_attendance_logs')
    op.drop_index(op.f('ix_employee_face_profiles_employee_id'), table_name='employee_face_profiles')
    op.drop_table('employee_face_profiles')
    # ### end Alembic commands ###
