"""employee shift assignments

Revision ID: dc7061332734
Revises: a533891375cd
Create Date: 2025-09-14 18:24:15.405215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7061332734'
down_revision: Union[str, Sequence[str], None] = 'a533891375cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_shift_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_emp_shift_range', 'employee_shift_assignments', ['employee_id', 'start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_employee_shift_assignments_employee_id'), 'employee_shift_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_shift_assignments_end_date'), 'employee_shift_assignments', ['end_date'], unique=False)
    op.create_index(op.f('ix_employee_shift_assignments_shift_id'), 'employee_shift_assignments', ['shift_id'], unique=False)
    op.create_index(op.f('ix_employee_shift_assignments_start_date'), 'employee_shift_assignments', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_shift_assignments_start_date'), table_name='employee_shift_assignments')
    op.drop_index(op.f('ix_employee_shift_assignments_shift_id'), table_name='employee_shift_assignments')
    op.drop_index(op.f('ix_employee_shift_assignments_end_date'), table_name='employee_shift_assignments')
    op.drop_index(op.f('ix_employee_shift_assignments_employee_id'), table_name='employee_shift_assignments')
    op.drop_index('ix_emp_shift_range', table_name='employee_shift_assignments')
    op.drop_table('employee_shift_assignments')
    # ### end Alembic commands ###
